### PR TITLE
Mobiperf debug

### PR DESCRIPTION
**Pull request by quietbamboo**
A bug fix reviewed here

http://speedometer-reviews.appspot.com/12001/

The review feedback of 12001 are fixed in later commits.
There are some conflict and mistake made in the middle, but I fixed it in the end.

### CODE REVIEW

**Comment by quietbamboo** [comment]
Please take a quick look before I merge this request.
Since the review of 12001 are only a few format problems, I didn't send another review there, but instead submit a pull request here

**Comment by mdwelsh** [comment]
Looks OK but can't be merged now - please merge and submit ....

**Comment by quietbamboo** [comment]
Closing this pull request right now, making a new one

**Comment by quietbamboo** [comment]
This is done here https://github.com/Mobiperf/MobiPerf/pull/77

**Pull request closed without merging**
