### PR TITLE
Pull requests with 3 new commits for MobiPerf v0.1 Beta

### PR DESCRIPTION
**Pull request by quietbamboo**
Includes three new commits fixing all comments from @mdwelsh

### CODE REVIEW

**Comment by gavaletz** [comment]
Please see this for how to write a commit message.  https://gist.github.com/1475276  It really is important.  Since this is open source, one day your future employer may consider the quality of your commit messages as part of your job interview.

**Comment by quietbamboo** [comment]
In reply to matt:

This is some error, I already fixed it in my branch.

**Comment by quietbamboo** [comment]
@gavaletz Good information. Will add more descriptive commit messages.

Thanks

**Comment by mdwelsh** [comment]
LGTM, but a few issues here:

1) When you update the code based on a previous comment, please REPLY to the comment with "Done" so I  know it was taken care of. Unfortunately it is very hard in github for me to connect the changes you make in later commits with earlier comments.

2) Github says "this pull request cannot be automatically merged." This might be because there are some conflicts in files that have changed since the last time you updated the pull request? Can you please merge with HEAD in the 'master' branch and update the pull request accordingly?

**Comment by quietbamboo** [comment]
OK, I will close this pull request and make a new one

**Pull request closed without merging**
