### PR TITLE
Config for enabling (and securing) data validation.

### PR DESCRIPTION
**Pull request by drchoffnes**

### CODE REVIEW

**Comment by mdwelsh** [comment]
This can't be auto merged, please update your branch and try again.

**Comment by drchoffnes** [comment]
Sorry for the ugly commit -- I didn't realize that it would include all the files from updating the branch. Let me retry...

**Comment by drchoffnes** [comment]
If you have any advice on how to clean up this commit, please let me know. I haven't been able to figure it out...

**Comment by mdwelsh** [comment]
Eeep. Can you try using git rebase instead of git merge? What you can do is revert your latest commit (6e1f76e) and then git rebase master from your dev branch.

**Comment by drchoffnes** [comment]
I think it's better now. All this for a spacing change. Can't wait to
start using the new code review system instead.

On Tue, May 29, 2012 at 7:18 PM, Matt Welsh
reply@reply.github.com
wrote:

**Pull request merged**
