### PR TITLE
directory reorg

### PR DESCRIPTION
**Pull request by drchoffnes**
This is the android directory reorg I suggested. As mentioned in the comments, there were slight changes to the .project and .classpath files, likely due to different android SDKs. Not sure what to do about that.

Otherwise, I changed the server code to add another admin user.

### CODE REVIEW

**Comment by mdwelsh** [comment]
Can you confirm this still builds and runs the Android app with this setup?

**Comment by drchoffnes** [comment]
Yup, it's running and reporting data to GAE (and has been for ~24 hrs :-)

On Mar 8, 2012, at 3:24 PM, Matt Welsh
reply@reply.github.com
wrote:

**Comment by mdwelsh** [comment]
Junxian et al - you guys OK with this?

**Comment by quietbamboo** [comment]
Yes, it's fine. We will test it.

**Pull request merged**
