### PR TITLE
Data anonymization code

### PR DESCRIPTION
**Pull request by drchoffnes**
LGTM from http://speedometer-reviews.appspot.com/9001/.

### CODE REVIEW

**Comment by mdwelsh** [comment]
I am not sure what is going on here, but it looks like you have not synced with the latest version of Mobiperf in your own fork. Therefore, this would appear to be reverting back to the (abandoned) version of the Android app, which we want to avoid. Can you please re-sync your own fork and "git rebase" your changes on top of the latest code so only the commits that are related to anonymization appear in this pull request?

**Comment by drchoffnes** [comment]
I had been syncing with the latest version of mobiperf while developing the code. i think the problem is that dominic changed the code residing at 'mobiperf/master' after i had already synced with newer versions of the old mobiperf. i have absolutely no idea how to deal with this mess.

**Comment by mdwelsh** [comment]
This should be easy.

You create a new branch that pulls from to the upstream "master" branch on
Mobiperf/Mobiperf on github.

Then you "git rebase" your changes on top of that new branch. It will take
diffs from your current development branch (which upstreams from the old
code, but that doesn't matter) and re-apply them to the new branch.

Since all you have touched is the AppEngine code it should go in clean.

Then you can submit a pull request in the new branch.

In the worst case you can do this by hand by using "git diff" and then
"patch".

**Comment by drchoffnes** [comment]
Looks like there isn't an easy fix here. AFAICT the new master doesn't have
any of the appengine changes that were previously pulled into (old) master
so even the patches from diff are failing. It would be great if Dominic
could go in and make sure all the non-android commits are also pulled into
new master from the old one.

**Comment by mdwelsh** [comment]
Huh. I thought we were up to date in the server directory and the only
changes were in the Android code when we committed that. Can you look at
the git logs and see which commits we're missing there? This should be
trivial to fix... Use git checkout with the latest commit id in the server
directory and pass "server" as an extra argument and it should bring you up
to date....

**Comment by mdwelsh** [comment]
OK, I see what happened here - we did end up reverting the old speedometer
code in the server directory as well, and I meant - but somehow failed - to
roll that directory forward.

Dave, I can fix this tomorrow morning (I don't have the ability to do it at
home tonight unfortunately), or you can do it. It is not hard: You can use
"git checkout" to get the code back from the server directory in the
"umich" branch and commit it to "master".

Sorry about this.

**Comment by drchoffnes** [comment]
It would be great if you could do this when you get the chance. In my brief
time with git I have a tendency to fubar everything when doing anything
beyond simple tasks and I'd rather not do that to our shard repository.
Thanks!

**Comment by mdwelsh** [comment]
OK, let me take a stab at this when I get to the office later this morning.
Sorry for the borkage.

**Comment by mdwelsh** [comment]
Dave,

This should be fixed now. The Appengine code in the new 'master' branch should be identical to what is in the 'umich' branch (i.e., the head code before the rename).

Can you please send a new pull request against MobiPerf/master for these changes. (You can verify that it's the right set of changes by doing a 'git diff mobiperf/master' assuming you have 'mobiperf' set up as a remote.)

**Comment by drchoffnes** [comment]
Done, thanks for adding the server code back.

**Pull request closed without merging**
